---
title: "ChrisCode that Nathan Sent"
author: "Chloe Swick"
date: "2023-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
```


```{r}
rm(list = ls(all = TRUE))
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(ggplot2) # Data visualization
library(tidyr) # Tidy data management
library(dplyr)
library(cowplot)
sizex = 100 #size of the state grid
T=10 #time horizon for backward induction
a=20
b=.1
delta=1/1.2
r=.8
K=100
small=K/1000
xgrid = seq(small,K,length.out=sizex)

3

f = function(h,x){
  xnext = x + r*x*(1-x/K) - h
}

pi = function(h){
  profit = a*h-b*h^2
}

Payoff = function(h,x,V){ 
  #xnext = max(small,f(h,x))
  xnext = f(h,x)
  Vnext = spline(x=xgrid,y=V,xout=xnext)
  negout = -(pi(h) + delta*Vnext$y)
return(negout)
}

DFall = data.frame()
Vnext = vector()
V = seq(0,0,length.out=sizex)

#Try payoff function
z=Payoff(.17992,.1,V)
  for(t in T:1)
  {
  print(t)
  for(i in 1:sizex)
  {
x = xgrid[i]
guess = x/2
low = 0 #lower bound on harvest
high = x + r*x*(1-x/K) #upper bound on harvest
Thing = optim(par=guess,fn=Payoff,lower=low,upper=high,x=x,V=V,method= 'L-BFGS-B')
hstar = Thing$par
Vstar = -Thing$value
Vnext[i] = Vstar
DFnow = data.frame(time=t,x=x,hstar=hstar,Vstar=Vstar)

4

DFall = bind_rows(DFall,DFnow)
}
V = Vnext
}
Ph = ggplot(data=DFall) +
geom_path(aes(x=x,y=hstar,color=factor(time)),size=1.3) +
xlab("Stock, x") +
ylab("Harvest, h") +
scale_color_discrete(name="Year") +
theme_bw() +
theme(legend.position = "none")
Ph
PV = ggplot(data=DFall) +
geom_path(aes(x=x,y=Vstar,color=factor(time)),size=1.3) +
xlab("Stock, x") +
ylab("Value Function, V") +
scale_color_discrete(name="Year") +
theme_bw()
#PV
#Forward Simulation
DFopt = DFall %>% filter(time==1)
hpol = DFopt$hstar
xpol = DFopt$x
xsim=vector()
hsim=vector()
xsim[1]=K/10
Tsim = seq(1,20)
for(tt in Tsim)
{
Thing = spline(x=xpol,y=hpol,xout=xsim[tt])
hsim[tt] = Thing$y
if(tt<max(Tsim))
{
xsim[tt+1] = f(h=hsim[tt],x=xsim[tt])
}

5

}
DFsim = data.frame(time=Tsim,xsim=xsim,hsim=hsim)
Pxsim = ggplot(data=DFsim) +
geom_line(aes(x=time,y=xsim),color="blue",size=1.5) +
xlab("Time") +
ylab("Stock, x") +
theme_bw()
#Pxsim
Phsim = ggplot(data=DFsim) +
geom_line(aes(x=time,y=hsim),color="blue",size=1.5) +
xlab("Time") +
ylab("Harvest, h") +
theme_bw()
#Phsim
Pall = plot_grid(Ph,PV,Pxsim,Phsim,ncol=2,nrow=2)
Pall
ggsave(filename="../Fig1.png",plot=Pall,width=6,height=5,unit="in")
```





















